#.travis.yml

language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g ionic cordova
  - npm install

script:
  - ionic build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change